### ISSUE TITLE
Overhaul ABI packs framework

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/lattice-manager#183]
We currently load a hardcoded set of ABI packs and use those to lookup JSON files in a GridPlus S3 bucket ([example](https://gridplus-public.s3.amazonaws.com/v2_gnosis.json)). This means that to add an ABI pack, someone at GridPlus needs to build the ABI definitions using [this script](https://gist.github.com/alex-miller-0/e02c58577c59ddea67434624289a7032)

This is not ideal. Instead, we should do the following:

* Create a new Github repo with a curated list of smart contract addresses and ABI definitions. Each pack in this repo should contain a name, links to documentation, lists of smart contracts, and the associated ABI definitions. These should still be stored in JSON files. The definitions should be pre-built before they are merged into the repo, which can be done with the gist above or a modified version of it. So we should write a script and include it in the repo so that adding new packs is easy.
* Switch this repo to point to the github repo and load the first N packs. The order would probably need to be curated as counting installs would be extra work, but we could go that route too.
* Allow searching for packs via the github repo, i.e. we need a way to request packs outside of the first N
* Document the new repo with instructions on how to create a pull request to add a new pack

**Comment by douglance** [comment]
I created the new repo here: https://github.com/GridPlus/abi-pack-framework
