### ISSUE TITLE
Third party connections no longer showing up

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/lattice-manager#186]
The data format probably changed. Need to look into it. At a minimum people should see MetaMask as a connection they can manage.

**Comment by alex-miller-0** [comment]
The issue appears to be the following:

1. When we connect to a keyring (this is basically just an external connection module), we save the login credentials to local storage inside of `main.js` (`saveKeyringLogin()`). This saves an object to the following location: `storage.settings.keyringLogins[this.state.name]`
2. When the app comes up, it pulls in the settings from local storage (in `getLocalStorageSettings()` in `helpers.js`)
3. When any setting is updated in the settings menu by the user, it overwrites the entire settings object (`submit()` in `settings.js`)

Two things should be fixed here:

* We should not be saving to localstorage outside of `settings.js`, so the `saveKeyringLogin` logic should be moved there.
* Instead of overwriting the object entirely (`storage.settings = this.state.settings`) this should be done for each non-null key in `this.state.settings`

**Comment by douglance** [comment]
@alex-miller-0 How would I test connecting to a keyring?

**Comment by alex-miller-0** [comment]
@douglance you can test with MetaMask. Otherwise you can just type in `localhost:300?keyring=foobar` and create the pairing
