### ISSUE TITLE
Allow user to add multiple address tags at once and make labels clearer

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/lattice-manager#202]
Here's our current add tag modal: 
![image](https://user-images.githubusercontent.com/7378490/148454683-18595d91-a08c-415e-a382-9be40debd90c.png)

We should make two changes:

1. Allow the user to add multiple tags at a time (there can be a little `+` button in the modal which opens another duplicate form for the additional tag
2. The labels are not super obvious. Perhaps we could put a `Tag` object next to each form item? I'd like the user to clearly see which line is supposed to be the address and which is supposed to be the human readable tag.

**Comment by douglance** [comment]
Are we planning on allowing users to add addresses from other networks here too?

**Comment by alex-miller-0** [comment]
Network isn't functionally relevant here. We could make that more clear and say something like "You can add addresses for *any network*"
