### ISSUE TITLE
Block auto-retry with pairing

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/lattice-manager#209]
**This is a pretty high priority issue**

I just ran into the following:

1. Reset my network module, getting a new device ID in the process
2. Went to lattice.gridplus.io and tried to log in with the new device ID
3. It tried to pair, since it did not recognize the device ID
4. When I entered the code, it showed the error screen on the Lattice but immediately retried
5. It kept retrying. I basically never had time to read the error screen

For the pairing component we should show an error and retry button when the pairing process fails. We should not auto retry. If we do, users will have no idea what is going wrong and it will appear super buggy. Users need to be able to read the error screen on the Lattice.

---

Please note that in SDK v0.9.3 I have added a retry mechanism which may be relevant here: https://github.com/GridPlus/gridplus-sdk/pull/210/files#diff-627fe08d8bba6a4fa76e7c5ed36ef6f16d126733e65e19236b391de0d34f1fe0R662-R694

We need to be sure what type of error comes back so it doesn't auto-retry in the SDK. If it does, we need to find some workaround.

**Update:** I don't think the new SDK retry logic will have any effect on this. I just tried the same process with the SDK test and it did not retry the pairing.

**Comment by douglance** [comment]
I followed your steps, but I'm not able to get it to try to pair without refreshing the page. 

I tested on Chrome and Firefox.

I'm stepping through the code to see what might be happening.
