### ISSUE TITLE
Remove strict check on adding kv file

### ISSUE THREAD

**Issue by alex-miller-0** [GridPlus/lattice-manager#220]
We wanted to validate that an address tag is a valid Ethereum address, but as we support more assets this restriction will need to be removed. Honestly it doesn't serve much purpose except to prevent people from saving useless data.

![image](https://user-images.githubusercontent.com/7378490/153766378-f76a5503-f775-4d72-b00b-d88f9c7d0659.png)

**Comment by alex-miller-0** [comment]
Also, we need to get smarter about where the links direct. For example, Solana addresses should link to solscan. We may just want the addresses to not include URLs

**Comment by douglance** [comment]
@alex-miller-0 I looked into trying to detect which network a given address is from based on it's content, and there isn't a universally accepted solution as far as I can tell. Do you have any insight into how that could be accomplished easily?

**Comment by alex-miller-0** [comment]
Not really.. the biggest problem is that ETH addresses look the same across networks. I think we should just get rid of the link tbh

**Comment by douglance** [comment]
> Not really.. the biggest problem is that ETH addresses look the same across networks. I think we should just get rid of the link tbh

Ok. 

Would it make sense, in the future, to allow uses to specify which network the given address should be associated with?

**Comment by alex-miller-0** [comment]
> Would it make sense, in the future, to allow uses to specify which network the given address should be associated with?

Yes it would. That's an extra step most users won't take but it would be worth including.
